---
title: Ryuta Shitomi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Portfolio and Blog
description: devlopr-jekyll is a Jekyll Theme Built For Developers
url: https://ryuta-s.github.io
baseurl: ''
urls:
- text: Blog
  url: "/blog"
- text: About Me
  url: "/about"
- text: Styleguide
  url: "/styleguide"
author_logo: home_logo.png
author: Ryuta Shitomi
author_bio: 'NAIST M1.　Interest: computer vision, machine learning.'
author_email: ''
author_location: Nara,Japan
author_website_url: http://ryuta-s.github.io
author_work_experiences:
- company_name: グローバルウォーカーズ株式会社
  company_logo: global_walkers_logo.png
  company_url: https://www.globalwalkers.co.jp
  designation: Deep Learning Engineer Internship
  description: 2019/2 ~ 2019/11. セマンティックセグメンテーションモデルの開発
  visibility: true
author_education_details:
- college_logo: kgu_logo_new.png
  college_name:
  - name: 情報学部　情報通信工学科
  - name: 画像情報メディア研究室
    url: https://www.ns.kogakuin.ac.jp/~wwa1071/
  college_url: https://www.kogakuin.ac.jp
  college_degree: 工学院大学
  description: 2016/4 ~ 2020/3 Bachelor of Engineering
  visibility: true
- college_logo: naist_logo.jpg
  college_name:
  - name: 先端科学技術研究科　情報科学領域
  - name: 光メディアインタフェース研究室
    url: http://omilab.naist.jp/index-jp.html
  college_url: https://www.naist.jp
  college_degree: 奈良先端科学技術大学院大学
  description: 2020/4 ~
  visibility: true
author_project_details:
- project_thumbnail: finding_lane.gif
  project_title: Finding Lane
  project_description: 車線検知プログラム
  project_url: https://github.com/Ryuta-S/CarND-Advanced-Lane-Lines
  visibility: true
- project_thumbnail: traffic_sign_classifier.gif
  project_title: traffic sign classifier
  project_description: 道路標識の認識プログラム
  project_url: https://github.com/Ryuta-S/traffic_sign_classifier
  visibility: true
- project_thumbnail: kalmanfiler.gif
  project_title: kalman filter
  project_description: カルマンフィルターを用いた自己位置推定プログラム
  project_url: https"//github.com/Ryuta-S/
  visibility: false
github_username: Ryuta-S
linkedin_username: ryutashitomi
wakatime_username: Ryuta_S
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - development
